export const Article = {
  GET_ARTICLE: 'GET_ARTICLE',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
};

export const LOGOUT = 'LOGOUT';

export const Auth = {
  SAVE_LOGIN: 'SAVE_LOGIN',
  LOGIN: 'LOGIN',
  OAUTH_LOGIN: 'OAUTH_LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  LOADING: 'LOADING',
};
