export const Article = {
  GET_ARTICLE: 'GET_ARTICLE',
  SET_ARTICLE: 'SET_ARTICLE',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
};

export const LOGOUT = 'LOGOUT';

export const Auth = {
  SAVE_LOGIN: 'SAVE_LOGIN',
  LOGIN: 'LOGIN',
  OAUTH_LOGIN: 'OAUTH_LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  LOADING: 'LOADING',
};

export const Publisher = {
  GET_ARTICLES: 'GET_PUBLISHER_ARTICLES',
  SET_ARTICLES: 'SET_PUBLISHER_ARTICLES',
};
