version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  admin_api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://mongo_db:27017/publishers
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
