export const Publisher = {
  GET_ARTICLES: 'GET_PUBLISHER_ARTICLES',
  SET_ARTICLES: 'SET_PUBLISHER_ARTICLES',
  GET_ARTICLE: 'GET_PUBLISHER_ARTICLE',
  SET_ARTICLE: 'SET_PUBLISHER_ARTICLE',
};

export const Comment = {
  CREATE_COMMENT: 'CREATE_COMMENT',
};
